### ISSUE TITLE
Old SqlDataProvider DLL not cleaned up during upgrade installation

### ISSUE THREAD

**Issue by david-poindexter** [mitchelsellers/dnnDocuments#7]
The following error is displayed post-upgrade from older versions (in my case 3.1.6) of the module.

AbsoluteURL:
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:ee3fa721-672d-458b-b3f4-61771cf3a268
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:tDqB15mhfcSYMuHyBRe0uQ==
Message:The type initializer for 'DotNetNuke.Modules.Documents.DataProvider' threw an exception.
StackTrace:
   at DotNetNuke.Modules.Documents.DocumentController.GetDocuments(Int32 ModuleId, Int32 PortalId)
   at DotNetNuke.Modules.Documents.DocumentController.GetSearchItems(ModuleInfo ModInfo)
   at DotNetNuke.Services.Search.ModuleIndexer.GetSearchIndexItems(Int32 portalId)
InnerMessage:Value cannot be null. Parameter name: type
InnerStackTrace:
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at DotNetNuke.Framework.Reflection.CreateObject(String ObjectProviderType, String ObjectProviderName, String ObjectNamespace, String ObjectAssemblyName, Boolean UseCache, Boolean fixAssemblyName)
   at DotNetNuke.Framework.Reflection.CreateObject(String ObjectProviderType, String ObjectNamespace, String ObjectAssemblyName)
   at DotNetNuke.Modules.Documents.DataProvider.CreateProvider()
   at DotNetNuke.Modules.Documents.DataProvider..cctor()
Source:DotNetNuke.Modules.Documents
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:

Upon closer investigation it was determined the old **DotNetNuke.Modules.Documents.SqlDataProvider.dll** was left in place during the upgrade.  It should have been removed.

**Comment by mitchelsellers** [comment]
Did you try a direct upgrade?  Due to some issues I think a stepped upgrade was needed.

I'll have a look.

**Comment by david-poindexter** [comment]
Yes, it was a direct upgrade because that was the only install package available and there was no documented upgrade path that I could find.

**Comment by david-poindexter** [comment]
Thanks @mitchelsellers!
